### ISSUE TITLE
Different stats because of different sources.

### ISSUE THREAD

**Issue by MezianeHadjadj** [dz-experts/stats-api#2]
Stats api give different values comparing to gender api (Confirmed number is different from( male+ female cases ), maybe because we are using different data source for stats?
What about using same source as `/wilayas` api and get stats out of it?

**Comment by MezianeHadjadj** [comment]
what do you think @sohaibafifi ?, if you agree i can open a pr.

**Comment by MezianeHadjadj** [comment]
also maybe better if we include gender api into stats api?, to have one endpoint for general stats?

**Comment by sohaibafifi** [comment]
> What about using same source as `/wilayas` api and get stats out of it?

 Yes we can, using another endpoint. I noticed that the sum between wilayas is wrong!

**Comment by sohaibafifi** [comment]
Here is the [endpoint](https://services8.arcgis.com/yhz7DEAMzdabE4ro/arcgis/rest/services/DZ_COVID/FeatureServer/2/query?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Report%20asc&outSR=102100&resultOffset=0&resultRecordCount=1000&cacheHint=true)

**Comment by MezianeHadjadj** [comment]
Cool, then i will create a pr to update stats api.
This new endpoint will just give us `le cumul` which is `confirmed` cases. so I will use `/wilayas` api to get deaths/ recovered?, what do you think?
btw sum of death/recovered is same as actual stats api.
